# Generated by Django 2.0.4 on 2018-04-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartolas',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartolas',
            name='updated_at',
        ),
    ]
