# Generated by Django 2.0.4 on 2018-05-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas', '0003_auto_20180504_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodadas',
            fields=[
                ('rodadaId', models.AutoField(primary_key=True, serialize=False, verbose_name='rodadaId')),
                ('rodadaNome', models.CharField(max_length=50, verbose_name='rodadaNome')),
                ('rodadaRealizada', models.CharField(max_length=1, null=True, verbose_name='rodadaRealizada')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
                'ordering': ['rodadaId'],
            },
        ),
        migrations.AlterModelOptions(
            name='cartolas',
            options={'ordering': ['id'], 'verbose_name': 'Cartola', 'verbose_name_plural': 'Cartolas'},
        ),
        migrations.RenameField(
            model_name='cartolas',
            old_name='image',
            new_name='cartolaImagem',
        ),
    ]
